[package]
authors = ["Jason Knight <Jason@JasonKnight.us>"]
name = "mancala"
version = "0.1.0"

[dependencies]
bincode = "0.6.0"
docopt = "0.6"
env_logger = "0.3"
log = "0.3"
rand = "0.3.14"
rustc-serialize = "0.3"

[dev-dependencies]
env_logger = "0.3"
